use asset_store::temp_workspace::TempWorkspace;
use serde_json::Value;
use std::ffi::OsString;
use std::fs;
use std::os::unix::fs::{MetadataExt, PermissionsExt};
use std::path::Path;
use std::process::{Command, Output};

const BINARY: &str = env!("CARGO_BIN_EXE_anki-repository-maintenance");
const ORPHAN_HELPER_ENV: &str = "ANKI_REPOSITORY_MAINTENANCE_ORPHAN_TEST_ROOT";

#[test]
fn orphan_helper() {
    let Ok(root) = std::env::var(ORPHAN_HELPER_ENV) else {
        return;
    };
    let owner = TempWorkspace::create_under(Path::new(&root), "crash-leftover-smoke").unwrap();
    fs::write(owner.path().join("artifact"), [0x35_u8; 4096]).unwrap();
    std::mem::forget(owner);
}

#[test]
fn cli_clean_dry_run_apply_and_repeat_report_real_sizes() {
    let owner = TempWorkspace::create("repository-maintenance-cli-target-smoke").unwrap();
    let root = owner.path().join("checkout");
    let target = root.join("target");
    let temp_root = owner.path().join("tmp-sandbox");
    let cache_home = owner.path().join("cache-home");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(&target).unwrap();
    fs::create_dir_all(&temp_root).unwrap();
    fs::create_dir_all(&cache_home).unwrap();
    for name in ["unmarked-a", "unmarked-b", "unmarked-c"] {
        fs::write(temp_root.join(name), [0x61_u8; 128]).unwrap();
    }
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname=\"gc_cli_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n",
    )
    .unwrap();
    fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() {}\n").unwrap();
    fs::write(
        target.join("CACHEDIR.TAG"),
        b"Signature: 8a477f597d28d172789f06886806bc55\nGenerated by Cargo\n",
    )
    .unwrap();
    fs::write(target.join("synthetic-artifact"), [0x72_u8; 8192]).unwrap();
    let policy = owner.path().join("policy.toml");
    fs::write(
        &policy,
        "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1\ntarget_hard_limit_bytes=20000\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_hard_limit_bytes=3\nexternal_cache_goal_bytes=1\nexternal_cache_min_age_days=7\nexternal_cache_min_age_seconds=1\norphan_min_age_hours=24\norphan_min_age_seconds=3600\ntmp_top_entries=1\n",
    )
    .unwrap();

    let before = allocated_bytes(&target);
    let target_entries_before = directory_entry_names(&target);
    assert!(before > 2);
    let scan = invoke_scan(&root, &policy, &temp_root, &cache_home);
    assert!(
        scan.status.code().is_some_and(|code| code <= 1),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&scan.stdout),
        String::from_utf8_lossy(&scan.stderr)
    );
    let scan_json = json(&scan);
    assert_eq!(scan_json["cargo_target"]["action"], "warn");
    let temp_inventory = scan_json["tmp"]
        .as_array()
        .unwrap()
        .iter()
        .find(|inventory| inventory["root"] == temp_root.to_str().unwrap())
        .unwrap();
    assert_eq!(temp_inventory["largest"].as_array().unwrap().len(), 1);
    assert!(target.join("synthetic-artifact").exists());
    assert_eq!(directory_entry_names(&target), target_entries_before);
    assert_eq!(allocated_bytes(&target), before);
    let policy_text = fs::read_to_string(&policy).unwrap();
    fs::write(
        &policy,
        policy_text.replace("target_hard_limit_bytes=20000", "target_hard_limit_bytes=2"),
    )
    .unwrap();
    let dry = invoke(&root, &policy, &temp_root, &cache_home, false);
    assert!(
        dry.status.code().is_some_and(|code| code <= 1),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&dry.stdout),
        String::from_utf8_lossy(&dry.stderr)
    );
    let dry_json = json(&dry);
    assert!(matches!(
        dry_json["cargo_target"]["action"].as_str(),
        Some("delete" | "deferred")
    ));
    assert!(dry_json["cargo_target"]["bytes_before"].as_u64().unwrap() >= before);
    assert!(target.join("synthetic-artifact").exists());
    assert_eq!(directory_entry_names(&target), target_entries_before);
    assert_eq!(allocated_bytes(&target), before);
    if dry_json["cargo_target"]["action"] == "deferred" {
        return;
    }
    assert_eq!(dry_json["cargo_target"]["result"], "planned");

    let applied = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert!(
        applied.status.code().is_some_and(|code| code <= 1),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&applied.stdout),
        String::from_utf8_lossy(&applied.stderr)
    );
    let applied_json = json(&applied);
    assert_eq!(applied_json["cargo_target"]["result"], "removed");
    assert_eq!(applied_json["cargo_target"]["bytes_after"], 0);
    assert!(
        applied_json["cargo_target"]["bytes_freed"]
            .as_u64()
            .unwrap()
            >= before
    );
    assert!(!target.exists());

    let repeated = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert!(
        repeated.status.code().is_some_and(|code| code <= 1),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&repeated.stdout),
        String::from_utf8_lossy(&repeated.stderr)
    );
    let repeated_json = json(&repeated);
    assert_eq!(repeated_json["cargo_target"]["bytes_freed"], 0);
    assert!(
        repeated_json["cargo_target"]["bytes_before"]
            .as_u64()
            .unwrap()
            <= 1
    );
}

#[test]
fn cli_preserves_live_unknown_and_unverifiable_tmp_entries() {
    let owner = TempWorkspace::create("repository-maintenance-cli-temp-smoke").unwrap();
    let root = owner.path().join("checkout");
    let temp_root = owner.path().join("tmp-sandbox");
    let cache_home = owner.path().join("cache-home");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir(&temp_root).unwrap();
    fs::create_dir(&cache_home).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname=\"gc_tmp_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n",
    )
    .unwrap();
    fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() {}\n").unwrap();
    fs::write(temp_root.join("unmarked-foreign-entry"), [0x55_u8; 512]).unwrap();
    let policy = owner.path().join("policy.toml");
    fs::write(
        &policy,
        "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1048576\ntarget_hard_limit_bytes=2097152\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_hard_limit_bytes=3145728\nexternal_cache_goal_bytes=1048576\nexternal_cache_min_age_days=7\nexternal_cache_min_age_seconds=60\norphan_min_age_hours=24\norphan_min_age_seconds=3600\ntmp_top_entries=20\n",
    )
    .unwrap();

    let live = TempWorkspace::create_under(&temp_root, "live-cli-smoke").unwrap();
    let orphan = Command::new(std::env::current_exe().unwrap())
        .args(["--exact", "orphan_helper", "--nocapture"])
        .env(ORPHAN_HELPER_ENV, &temp_root)
        .output()
        .unwrap();
    assert!(
        orphan.status.success(),
        "{}",
        String::from_utf8_lossy(&orphan.stderr)
    );
    let live_path = live.path().to_path_buf();
    let run = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert!(
        run.status.code().is_some_and(|code| code <= 1),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&run.stdout),
        String::from_utf8_lossy(&run.stderr)
    );
    let report = json(&run);
    assert!(temp_root.join(format!("anki-decks-{}", uid())).exists());
    assert!(live_path.exists());
    assert!(temp_root.join("unmarked-foreign-entry").exists());
    let rows = report["project_temp"].as_array().unwrap();
    assert!(rows.iter().any(|row| {
        row["action"] == "deferred"
            && row["live"] == Value::Null
            && row["result"] == "unverified_or_fresh"
            && row["bytes_before"].as_u64().unwrap_or(0) > 0
    }));
    assert!(
        rows.iter()
            .any(|row| row["action"] == "deferred" && row["live"] == true)
    );
    assert!(report["tmp"].as_array().unwrap().iter().any(|inventory| {
        inventory["largest"].as_array().unwrap().iter().any(|row| {
            row["path"]
                .as_str()
                .is_some_and(|path| path.ends_with("unmarked-foreign-entry"))
                && row["ownership"] == "unknown"
        })
    }));
}

#[test]
fn cli_managed_external_cache_is_touched_by_run_and_pruned_after_minimum_age() {
    let owner = TempWorkspace::create("repository-maintenance-cli-cache-smoke").unwrap();
    let root = owner.path().join("checkout");
    let temp_root = owner.path().join("tmp-sandbox");
    let cache_home = owner.path().join("cache-home");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir(&temp_root).unwrap();
    fs::create_dir(&cache_home).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname=\"gc_cache_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n",
    )
    .unwrap();
    fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() {}\n").unwrap();
    let policy = owner.path().join("policy.toml");
    fs::write(
        &policy,
        "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1048576\ntarget_hard_limit_bytes=2097152\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_hard_limit_bytes=1\nexternal_cache_goal_bytes=0\nexternal_cache_min_age_days=7\nexternal_cache_min_age_seconds=1\norphan_min_age_hours=24\norphan_min_age_seconds=3600\ntmp_top_entries=20\n",
    )
    .unwrap();

    let initialized = Command::new(BINARY)
        .args([
            "cache",
            "init",
            "--id",
            "cache-smoke",
            "--workspace-root",
            root.to_str().unwrap(),
            "--json",
        ])
        .env("XDG_CACHE_HOME", &cache_home)
        .output()
        .unwrap();
    assert!(
        initialized.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&initialized.stdout),
        String::from_utf8_lossy(&initialized.stderr)
    );
    let cache_dir = cache_home.join("anki-decks/repository-maintenance/cache-smoke");
    let target_dir = cache_dir.join("target");
    let invoked = Command::new(BINARY)
        .args([
            "cache",
            "run",
            "--id",
            "cache-smoke",
            "--workspace-root",
            root.to_str().unwrap(),
            "--json",
            "--",
            "/bin/sh",
            "-c",
            "test \"$CARGO_TARGET_DIR\" = \"$CARGO_BUILD_TARGET_DIR\" && test \"$CARGO_TARGET_DIR\" = \"$CARGO_BUILD_BUILD_DIR\"",
        ])
        .env("XDG_CACHE_HOME", &cache_home)
        .output()
        .unwrap();
    assert!(
        invoked.status.success(),
        "{}",
        String::from_utf8_lossy(&invoked.stdout)
    );
    let marker_path = cache_dir.join(".anki-decks-build-cache.json");
    let mut marker: serde_json::Value =
        serde_json::from_slice(&fs::read(&marker_path).unwrap()).unwrap();
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    marker["last_used_unix_seconds"] = (now - 3600).into();
    fs::write(&marker_path, serde_json::to_vec(&marker).unwrap()).unwrap();
    fs::create_dir_all(&target_dir).unwrap();
    fs::write(
        target_dir.join("CACHEDIR.TAG"),
        b"Signature: 8a477f597d28d172789f06886806bc55\nGenerated by Cargo\n",
    )
    .unwrap();
    fs::write(target_dir.join("synthetic-artifact"), [0x44_u8; 8192]).unwrap();
    let cache_entries_before = directory_entry_names(&target_dir);
    let cache_bytes_before = allocated_bytes(&target_dir);

    let dry_run = invoke(&root, &policy, &temp_root, &cache_home, false);
    assert!(
        dry_run.status.code().is_some_and(|code| code <= 1),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&dry_run.stdout),
        String::from_utf8_lossy(&dry_run.stderr)
    );
    let dry_report = json(&dry_run);
    assert!(
        dry_report["external_build_caches"]
            .as_array()
            .unwrap()
            .iter()
            .any(|candidate| candidate["action"] == "delete")
    );
    assert_eq!(directory_entry_names(&target_dir), cache_entries_before);
    assert_eq!(allocated_bytes(&target_dir), cache_bytes_before);

    let pruned = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert!(
        pruned.status.code().is_some_and(|code| code <= 1),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&pruned.stdout),
        String::from_utf8_lossy(&pruned.stderr)
    );
    let report = json(&pruned);
    assert!(report["external_cache_bytes_before"].as_u64().unwrap() > 1);
    assert!(report["external_cache_bytes_freed"].as_u64().unwrap() > 1);
    assert!(!target_dir.exists());
}

fn invoke(root: &Path, policy: &Path, temp_root: &Path, cache_home: &Path, apply: bool) -> Output {
    let runtime = cache_home.join("runtime");
    fs::create_dir_all(&runtime).unwrap();
    fs::set_permissions(&runtime, fs::Permissions::from_mode(0o700)).unwrap();
    let mut command = Command::new(BINARY);
    command
        .args([
            "clean",
            "--workspace-root",
            root.to_str().unwrap(),
            "--policy",
            policy.to_str().unwrap(),
            "--temp-root",
            temp_root.to_str().unwrap(),
            "--json",
        ])
        .env("XDG_CACHE_HOME", cache_home)
        .env("XDG_RUNTIME_DIR", runtime);
    if apply {
        command.arg("--apply");
    }
    command.output().unwrap()
}

fn invoke_scan(root: &Path, policy: &Path, temp_root: &Path, cache_home: &Path) -> Output {
    let runtime = cache_home.join("runtime");
    fs::create_dir_all(&runtime).unwrap();
    fs::set_permissions(&runtime, fs::Permissions::from_mode(0o700)).unwrap();
    Command::new(BINARY)
        .args([
            "scan",
            "--workspace-root",
            root.to_str().unwrap(),
            "--policy",
            policy.to_str().unwrap(),
            "--temp-root",
            temp_root.to_str().unwrap(),
            "--json",
        ])
        .env("XDG_CACHE_HOME", cache_home)
        .env("XDG_RUNTIME_DIR", runtime)
        .output()
        .unwrap()
}

fn json(output: &Output) -> Value {
    serde_json::from_slice(&output.stdout).unwrap_or_else(|error| {
        panic!(
            "invalid JSON ({error}): {}",
            String::from_utf8_lossy(&output.stdout)
        )
    })
}

fn allocated_bytes(path: &Path) -> u64 {
    let mut total = 0_u64;
    for entry in fs::read_dir(path).unwrap() {
        let entry = entry.unwrap();
        let metadata = entry.metadata().unwrap();
        total = total.saturating_add(metadata.blocks() * 512);
    }
    total
}

fn directory_entry_names(path: &Path) -> Vec<OsString> {
    let mut entries = fs::read_dir(path)
        .unwrap()
        .map(|entry| entry.unwrap().file_name())
        .collect::<Vec<_>>();
    entries.sort();
    entries
}

fn uid() -> u32 {
    use std::os::unix::fs::MetadataExt;
    fs::metadata("/proc/self").unwrap().uid()
}
