use asset_store::temp_workspace::TempWorkspace;
use serde_json::Value;
use std::ffi::OsString;
use std::fs;
use std::os::unix::fs::{MetadataExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Output, Stdio};
use std::time::{Duration, Instant};

const BINARY: &str = env!("CARGO_BIN_EXE_anki-repository-maintenance");
const ORPHAN_HELPER_ENV: &str = "ANKI_REPOSITORY_MAINTENANCE_ORPHAN_TEST_ROOT";

#[test]
fn orphan_helper() {
    let Ok(root) = std::env::var(ORPHAN_HELPER_ENV) else {
        return;
    };
    let owner = TempWorkspace::create_under(Path::new(&root), "crash-leftover-smoke").unwrap();
    fs::write(owner.path().join("artifact"), [0x35_u8; 4096]).unwrap();
    std::mem::forget(owner);
}

#[test]
fn cli_clean_dry_run_apply_and_repeat_report_real_sizes() {
    let owner = TempWorkspace::create("repository-maintenance-cli-target-smoke").unwrap();
    let root = owner.path().join("checkout");
    let target = root.join("target");
    let temp_root = owner.path().join("tmp-sandbox");
    let cache_home = owner.path().join("cache-home");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(&target).unwrap();
    fs::create_dir_all(&temp_root).unwrap();
    fs::create_dir_all(&cache_home).unwrap();
    for name in ["unmarked-a", "unmarked-b", "unmarked-c"] {
        fs::write(temp_root.join(name), [0x61_u8; 128]).unwrap();
    }
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname=\"gc_cli_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n",
    )
    .unwrap();
    fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() {}\n").unwrap();
    fs::write(
        target.join("CACHEDIR.TAG"),
        b"Signature: 8a477f597d28d172789f06886806bc55\nGenerated by Cargo\n",
    )
    .unwrap();
    fs::write(target.join("synthetic-artifact"), [0x72_u8; 8192]).unwrap();
    let policy = owner.path().join("policy.toml");
    fs::write(
        &policy,
        "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1\ntarget_hard_limit_bytes=20000\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_hard_limit_bytes=3\nexternal_cache_goal_bytes=1\nexternal_cache_min_age_days=7\nexternal_cache_min_age_seconds=1\norphan_min_age_hours=24\norphan_min_age_seconds=3600\ntmp_top_entries=1\n",
    )
    .unwrap();

    let before = allocated_bytes(&target);
    let target_entries_before = directory_entry_names(&target);
    assert!(before > 2);
    let scan = invoke_scan(&root, &policy, &temp_root, &cache_home);
    assert!(
        scan.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&scan.stdout),
        String::from_utf8_lossy(&scan.stderr)
    );
    let scan_json = json(&scan);
    assert_eq!(scan_json["cargo_target"]["action"], "warn");
    assert_eq!(scan_json["mode"], "scan");
    assert_eq!(scan_json["cargo_target"]["result"], "not_needed");
    let temp_inventory = scan_json["tmp"]
        .as_array()
        .unwrap()
        .iter()
        .find(|inventory| inventory["root"] == temp_root.to_str().unwrap())
        .unwrap();
    assert_eq!(temp_inventory["largest"].as_array().unwrap().len(), 1);
    assert!(target.join("synthetic-artifact").exists());
    assert_eq!(directory_entry_names(&target), target_entries_before);
    assert_eq!(allocated_bytes(&target), before);
    let policy_text = fs::read_to_string(&policy).unwrap();
    fs::write(
        &policy,
        policy_text.replace("target_hard_limit_bytes=20000", "target_hard_limit_bytes=2"),
    )
    .unwrap();
    let dry = invoke(&root, &policy, &temp_root, &cache_home, false);
    assert!(
        dry.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&dry.stdout),
        String::from_utf8_lossy(&dry.stderr)
    );
    let dry_json = json(&dry);
    assert_eq!(dry_json["cargo_target"]["action"], "delete", "{dry_json}");
    assert_eq!(dry_json["mode"], "dry-run");
    assert!(dry_json["cargo_target"]["bytes_before"].as_u64().unwrap() >= before);
    assert!(target.join("synthetic-artifact").exists());
    assert_eq!(directory_entry_names(&target), target_entries_before);
    assert_eq!(allocated_bytes(&target), before);
    assert_eq!(dry_json["cargo_target"]["result"], "planned");
    let exceeded = invoke_scan(&root, &policy, &temp_root, &cache_home);
    assert!(exceeded.status.success(), "{}", json(&exceeded));
    assert_eq!(json(&exceeded)["cargo_target"]["action"], "warn");
    assert_eq!(
        json(&exceeded)["cargo_target"]["result"],
        "threshold_exceeded"
    );

    let applied = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert!(
        applied.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&applied.stdout),
        String::from_utf8_lossy(&applied.stderr)
    );
    let applied_json = json(&applied);
    assert_eq!(applied_json["cargo_target"]["result"], "removed");
    assert_eq!(applied_json["cargo_target"]["bytes_after"], 0);
    assert!(
        applied_json["cargo_target"]["bytes_freed"]
            .as_u64()
            .unwrap()
            >= before
    );
    assert!(!target.exists());

    let repeated = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert!(
        repeated.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&repeated.stdout),
        String::from_utf8_lossy(&repeated.stderr)
    );
    let repeated_json = json(&repeated);
    assert_eq!(repeated_json["cargo_target"]["bytes_freed"], 0);
    assert!(
        repeated_json["cargo_target"]["bytes_before"]
            .as_u64()
            .unwrap()
            <= 1
    );
}

#[test]
fn cli_clean_reports_invalid_target_marker_as_fatal_and_preserves_target() {
    let owner = TempWorkspace::create("repository-maintenance-invalid-target-marker").unwrap();
    let root = owner.path().join("checkout");
    let target = root.join("target");
    let temp_root = owner.path().join("tmp");
    let cache_home = owner.path().join("cache-home");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(&target).unwrap();
    fs::create_dir_all(&temp_root).unwrap();
    fs::create_dir_all(&cache_home).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname=\"invalid_target_marker_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n",
    )
    .unwrap();
    fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() {}\n").unwrap();
    fs::write(target.join("CACHEDIR.TAG"), "not a Cargo marker\n").unwrap();
    fs::write(target.join("synthetic-artifact"), [0x71_u8; 8192]).unwrap();
    let policy = owner.path().join("policy.toml");
    fs::write(
        &policy,
        "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1\ntarget_hard_limit_bytes=2\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_min_age_days=7\norphan_min_age_hours=24\ntmp_top_entries=20\n",
    )
    .unwrap();

    let output = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert_eq!(output.status.code(), Some(1), "{}", json(&output));
    let report = json(&output);
    assert_eq!(report["cargo_target"]["action"], "error");
    assert_eq!(report["cargo_target"]["result"], "failed");
    assert!(report["cargo_target"]["error"].as_str().is_some());
    assert_eq!(report["fatal_errors"], 1);
    assert!(target.join("synthetic-artifact").exists());
}

#[test]
fn cli_preserves_live_unknown_and_unverifiable_tmp_entries() {
    let owner = TempWorkspace::create("repository-maintenance-cli-temp-smoke").unwrap();
    let root = owner.path().join("checkout");
    let temp_root = owner.path().join("tmp-sandbox");
    let cache_home = owner.path().join("cache-home");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir(&temp_root).unwrap();
    fs::create_dir(&cache_home).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname=\"gc_tmp_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n",
    )
    .unwrap();
    fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() {}\n").unwrap();
    fs::write(temp_root.join("unmarked-foreign-entry"), [0x55_u8; 512]).unwrap();
    let policy = owner.path().join("policy.toml");
    fs::write(
        &policy,
        "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1048576\ntarget_hard_limit_bytes=2097152\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_hard_limit_bytes=3145728\nexternal_cache_goal_bytes=1048576\nexternal_cache_min_age_days=7\nexternal_cache_min_age_seconds=60\norphan_min_age_hours=24\norphan_min_age_seconds=3600\ntmp_top_entries=20\n",
    )
    .unwrap();

    let live = TempWorkspace::create_under(&temp_root, "live-cli-smoke").unwrap();
    let orphan = Command::new(std::env::current_exe().unwrap())
        .args(["--exact", "orphan_helper", "--nocapture"])
        .env(ORPHAN_HELPER_ENV, &temp_root)
        .output()
        .unwrap();
    assert!(
        orphan.status.success(),
        "{}",
        String::from_utf8_lossy(&orphan.stderr)
    );
    let live_path = live.path().to_path_buf();
    let run = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert!(
        run.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&run.stdout),
        String::from_utf8_lossy(&run.stderr)
    );
    let report = json(&run);
    assert!(temp_root.join(format!("anki-decks-{}", uid())).exists());
    assert!(live_path.exists());
    assert!(temp_root.join("unmarked-foreign-entry").exists());
    let rows = report["project_temp"].as_array().unwrap();
    assert!(rows.iter().any(|row| {
        row["action"] == "deferred"
            && row["live"] == Value::Null
            && row["result"] == "unverified_or_fresh"
            && row["bytes_before"].as_u64().unwrap_or(0) > 0
    }));
    assert!(
        rows.iter()
            .any(|row| row["action"] == "deferred" && row["live"] == true)
    );
    assert!(report["tmp"].as_array().unwrap().iter().any(|inventory| {
        inventory["largest"].as_array().unwrap().iter().any(|row| {
            row["path"]
                .as_str()
                .is_some_and(|path| path.ends_with("unmarked-foreign-entry"))
                && row["ownership"] == "unknown"
        })
    }));
}

#[test]
fn cli_managed_external_cache_is_touched_by_run_and_pruned_after_minimum_age() {
    let owner = TempWorkspace::create("repository-maintenance-cli-cache-smoke").unwrap();
    let root = owner.path().join("checkout");
    let temp_root = owner.path().join("tmp-sandbox");
    let cache_home = owner.path().join("cache-home");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir(&temp_root).unwrap();
    fs::create_dir(&cache_home).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname=\"gc_cache_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n",
    )
    .unwrap();
    fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() {}\n").unwrap();
    let policy = owner.path().join("policy.toml");
    fs::write(
        &policy,
        "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1048576\ntarget_hard_limit_bytes=2097152\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_hard_limit_bytes=1\nexternal_cache_goal_bytes=0\nexternal_cache_min_age_days=7\nexternal_cache_min_age_seconds=1\norphan_min_age_hours=24\norphan_min_age_seconds=3600\ntmp_top_entries=20\n",
    )
    .unwrap();

    let initialized = Command::new(BINARY)
        .args([
            "cache",
            "init",
            "--id",
            "cache-smoke",
            "--workspace-root",
            root.to_str().unwrap(),
            "--json",
        ])
        .env("XDG_CACHE_HOME", &cache_home)
        .output()
        .unwrap();
    assert!(
        initialized.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&initialized.stdout),
        String::from_utf8_lossy(&initialized.stderr)
    );
    let cache_dir = cache_home.join("anki-decks/repository-maintenance/cache-smoke");
    let target_dir = cache_dir.join("target");
    let cargo = write_cargo(
        owner.path(),
        "test \"$CARGO_TARGET_DIR\" = \"$CARGO_BUILD_TARGET_DIR\" && test \"$CARGO_TARGET_DIR\" = \"$CARGO_BUILD_BUILD_DIR\"\n",
    );
    let runtime = private_runtime(&cache_home);
    let invoked = Command::new(BINARY)
        .args([
            "cache",
            "run",
            "--id",
            "cache-smoke",
            "--workspace-root",
            root.to_str().unwrap(),
            "--json",
            "--",
            cargo.to_str().unwrap(),
            "build",
        ])
        .env("XDG_CACHE_HOME", &cache_home)
        .env("XDG_RUNTIME_DIR", &runtime)
        .env("TMPDIR", &temp_root)
        .output()
        .unwrap();
    assert!(
        invoked.status.success(),
        "{}",
        String::from_utf8_lossy(&invoked.stdout)
    );
    let marker_path = cache_dir.join(".anki-decks-build-cache.json");
    let mut marker: serde_json::Value =
        serde_json::from_slice(&fs::read(&marker_path).unwrap()).unwrap();
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    marker["last_used_unix_seconds"] = (now - 3600).into();
    fs::write(&marker_path, serde_json::to_vec(&marker).unwrap()).unwrap();
    fs::create_dir_all(&target_dir).unwrap();
    fs::write(
        target_dir.join("CACHEDIR.TAG"),
        b"Signature: 8a477f597d28d172789f06886806bc55\nGenerated by Cargo\n",
    )
    .unwrap();
    fs::write(target_dir.join("synthetic-artifact"), [0x44_u8; 8192]).unwrap();
    let cache_entries_before = directory_entry_names(&target_dir);
    let cache_bytes_before = allocated_bytes(&target_dir);

    let dry_run = invoke(&root, &policy, &temp_root, &cache_home, false);
    assert!(
        dry_run.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&dry_run.stdout),
        String::from_utf8_lossy(&dry_run.stderr)
    );
    let dry_report = json(&dry_run);
    assert!(
        dry_report["external_build_caches"]
            .as_array()
            .unwrap()
            .iter()
            .any(|candidate| candidate["action"] == "delete")
    );
    assert_eq!(directory_entry_names(&target_dir), cache_entries_before);
    assert_eq!(allocated_bytes(&target_dir), cache_bytes_before);

    let pruned = invoke(&root, &policy, &temp_root, &cache_home, true);
    assert!(
        pruned.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&pruned.stdout),
        String::from_utf8_lossy(&pruned.stderr)
    );
    let report = json(&pruned);
    assert!(report["external_cache_bytes_before"].as_u64().unwrap() > 1);
    assert!(report["external_cache_bytes_freed"].as_u64().unwrap() > 1);
    assert!(!target_dir.exists());
}

struct CacheFixture {
    owner: TempWorkspace,
    root: PathBuf,
    cache_home: PathBuf,
    temp_root: PathBuf,
    policy: PathBuf,
    cache_dir: PathBuf,
}

impl CacheFixture {
    fn new() -> Self {
        let owner = TempWorkspace::create("maintenance-cli-regression").unwrap();
        let root = owner.path().join("checkout");
        let cache_home = owner.path().join("cache-home");
        let temp_root = owner.path().join("tmp");
        fs::create_dir_all(root.join("src")).unwrap();
        fs::create_dir_all(&cache_home).unwrap();
        fs::create_dir_all(&temp_root).unwrap();
        fs::write(root.join("Cargo.toml"), "[package]\nname=\"maintenance_cli_regression\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n").unwrap();
        fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
        fs::write(root.join("src/lib.rs"), "").unwrap();
        let policy = owner.path().join("policy.toml");
        fs::write(&policy, "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1\ntarget_hard_limit_bytes=2\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_min_age_days=7\norphan_min_age_hours=24\ntmp_top_entries=20\n").unwrap();
        let cache_dir = cache_home.join("anki-decks/repository-maintenance/fixture");
        let fixture = Self {
            owner,
            root,
            cache_home,
            temp_root,
            policy,
            cache_dir,
        };
        let initialized = fixture.command("init").output().unwrap();
        assert!(initialized.status.success(), "{}", json(&initialized));
        fixture
    }

    fn command(&self, action: &str) -> Command {
        let mut command = Command::new(BINARY);
        command
            .args(["cache", action, "--id", "fixture", "--workspace-root"])
            .arg(&self.root)
            .arg("--json")
            .env("XDG_CACHE_HOME", &self.cache_home)
            .env("XDG_RUNTIME_DIR", private_runtime(&self.cache_home))
            .env("TMPDIR", &self.temp_root);
        command
    }

    fn marker(&self) -> PathBuf {
        self.cache_dir.join(".anki-decks-build-cache.json")
    }

    fn age_marker(&self) {
        let mut marker: Value = serde_json::from_slice(&fs::read(self.marker()).unwrap()).unwrap();
        marker["last_used_unix_seconds"] = 1.into();
        fs::write(self.marker(), serde_json::to_vec(&marker).unwrap()).unwrap();
    }

    fn last_used(&self) -> u64 {
        let marker: Value = serde_json::from_slice(&fs::read(self.marker()).unwrap()).unwrap();
        marker["last_used_unix_seconds"].as_u64().unwrap()
    }
}

#[test]
fn cli_cache_run_rejects_directory_overrides_before_marker_or_child_changes() {
    let fixture = CacheFixture::new();
    let cargo = write_cargo(fixture.owner.path(), "touch \"$CHILD_RAN\"\n");
    let child_ran = fixture.owner.path().join("child-ran");
    for (name, contents) in [
        ("target.toml", "[build]\ntarget-dir=\"outside\"\n"),
        ("build.toml", "[build]\nbuild-dir=\"outside\"\n"),
    ] {
        fs::write(fixture.root.join(name), contents).unwrap();
    }
    let cases = [
        vec!["build", "--target-dir", "outside"],
        vec!["build", "--target-dir=outside"],
        vec!["build", "--config", "build.target-dir=\"outside\""],
        vec!["build", "--config=build.target-dir=\"outside\""],
        vec!["build", "--config", "build.build-dir=\"outside\""],
        vec!["build", "--config=build.build-dir=\"outside\""],
        vec!["build", "--config", "target.toml"],
        vec!["build", "--config=build.toml"],
        vec!["build", "-C", "outside"],
        vec!["--config", "build.target-dir=\"outside\"", "build"],
        vec!["--config=build.target-dir=\"outside\"", "build"],
        vec!["--config", "build.build-dir=\"outside\"", "build"],
        vec!["--config=build.build-dir=\"outside\"", "build"],
        vec!["--config", "target.toml", "build"],
        vec!["--config=build.toml", "build"],
        vec!["-C", "outside", "build"],
        vec!["-Coutside", "build"],
    ];
    let before = fs::read(fixture.marker()).unwrap();
    for args in cases {
        let output = fixture
            .command("run")
            .arg("--")
            .arg(&cargo)
            .args(&args)
            .env("CHILD_RAN", &child_ran)
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(2), "{args:?}: {}", json(&output));
        assert!(json(&output)["error"].as_str().is_some(), "{args:?}");
        assert_eq!(fs::read(fixture.marker()).unwrap(), before, "{args:?}");
        assert!(!child_ran.exists(), "{args:?}");
    }
    for args in [
        vec!["env", "cargo", "build"],
        vec!["/bin/sh", "-c", "cargo build"],
    ] {
        let output = fixture
            .command("run")
            .arg("--")
            .args(&args)
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(2), "{}", json(&output));
        assert!(json(&output)["error"].as_str().unwrap().contains("Cargo"));
        assert_eq!(fs::read(fixture.marker()).unwrap(), before);
    }

    fs::create_dir_all(fixture.root.join(".cargo")).unwrap();
    fs::write(
        fixture.root.join(".cargo/config.toml"),
        "[alias]\nescape = \"check --target-dir outside\"\n",
    )
    .unwrap();
    let alias = fixture
        .command("run")
        .arg("--")
        .arg(&cargo)
        .args(["escape", "--offline"])
        .env("CHILD_RAN", &child_ran)
        .output()
        .unwrap();
    assert_eq!(alias.status.code(), Some(2), "{}", json(&alias));
    assert!(
        json(&alias)["error"]
            .as_str()
            .unwrap()
            .contains("псевдоним")
    );
    assert_eq!(fs::read(fixture.marker()).unwrap(), before);
    assert!(!child_ran.exists());
    assert!(!fixture.root.join("outside").exists());
}

#[test]
fn cli_cache_run_does_not_parse_application_arguments_after_cargo_separator() {
    let fixture = CacheFixture::new();
    let cargo = write_cargo(
        fixture.owner.path(),
        "printf '%s\\n' \"$@\" > \"$CHILD_ARGS\"\n",
    );
    let child_args = fixture.owner.path().join("child-args");
    let output = fixture
        .command("run")
        .arg("--")
        .arg(&cargo)
        .args([
            "+stable",
            "run",
            "--",
            "--target-dir",
            "app-output",
            "--config",
            "аргумент приложения с пробелами",
            "-C",
            "application-value",
        ])
        .env("CHILD_ARGS", &child_args)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}\nstderr={}",
        json(&output),
        String::from_utf8_lossy(&output.stderr)
    );
    let args = fs::read_to_string(child_args).unwrap();
    for argument in [
        "+stable",
        "--target-dir",
        "app-output",
        "--config",
        "аргумент приложения с пробелами",
        "-C",
        "application-value",
    ] {
        assert!(args.lines().any(|line| line == argument), "{args}");
    }
}

#[test]
fn cli_cache_run_managed_directories_override_included_cargo_config() {
    let fixture = CacheFixture::new();
    let cargo_config_dir = fixture.root.join(".cargo");
    fs::create_dir_all(&cargo_config_dir).unwrap();
    let outside_target = fixture.owner.path().join("outside-target");
    let included = format!(
        "[build]\ntarget-dir = {}\n",
        toml::Value::String(outside_target.to_string_lossy().into_owned())
    );
    fs::write(cargo_config_dir.join("nested.toml"), included).unwrap();
    fs::write(
        cargo_config_dir.join("extra.toml"),
        "include = [\"nested.toml\"]\n",
    )
    .unwrap();

    let output = fixture
        .command("run")
        .arg("--")
        .arg("cargo")
        .args(["--config", ".cargo/extra.toml", "check", "--offline"])
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}\nstderr={}",
        json(&output),
        String::from_utf8_lossy(&output.stderr)
    );
    let report = json(&output);
    let managed_target = fixture.cache_dir.join("target");
    assert_eq!(report["target_dir"], managed_target.to_str().unwrap());
    assert!(managed_target.join("debug/deps").is_dir());
    assert!(
        !outside_target.exists(),
        "Cargo записал данные вне управляемого каталога сборки"
    );
}

#[test]
fn cli_cache_run_json_forwards_noise_preserves_exit_and_finishes_lifecycle() {
    let fixture = CacheFixture::new();
    let cargo = write_cargo(
        fixture.owner.path(),
        "printf 'диагностика дочерней команды в stdout\\n'\nprintf 'диагностика дочерней команды в stderr\\n' >&2\nprintf '%s\\n' \"$@\" >&2\ntest \"$CARGO_TARGET_DIR\" = \"$CARGO_BUILD_TARGET_DIR\" || exit 91\ntest \"$CARGO_TARGET_DIR\" = \"$CARGO_BUILD_BUILD_DIR\" || exit 92\nexit \"$CHILD_EXIT\"\n",
    );
    fixture.age_marker();
    let output = fixture
        .command("run")
        .arg("--")
        .arg(&cargo)
        .arg("build")
        .env("CHILD_EXIT", "37")
        .env("CARGO_TARGET_DIR", "outside-inherited-target")
        .env("CARGO_BUILD_TARGET_DIR", "outside-inherited-build-target")
        .env("CARGO_BUILD_BUILD_DIR", "outside-inherited-build")
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(37));
    assert_eq!(json(&output)["exit_code"], 37);
    assert_eq!(json(&output)["error"], Value::Null);
    assert_eq!(
        json(&output)["target_dir"],
        fixture.cache_dir.join("target").to_str().unwrap()
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("диагностика дочерней команды в stdout"),
        "{stderr}"
    );
    assert!(
        stderr.contains("диагностика дочерней команды в stderr"),
        "{stderr}"
    );
    assert!(stderr.contains("build.target-dir="), "{stderr}");
    assert!(stderr.contains("build.build-dir="), "{stderr}");
    assert!(
        stderr.contains(fixture.cache_dir.join("target").to_str().unwrap()),
        "{stderr}"
    );
    assert!(fixture.last_used() > 1);
    let next = fixture
        .command("run")
        .arg("--")
        .arg(&cargo)
        .arg("build")
        .env("CHILD_EXIT", "0")
        .output()
        .unwrap();
    assert!(next.status.success(), "{}", json(&next));
    assert_eq!(json(&next)["exit_code"], 0);
}

struct RunningChild(Option<Child>);

impl Drop for RunningChild {
    fn drop(&mut self) {
        if let Some(child) = self.0.as_mut() {
            let _ = child.kill();
            let _ = child.wait();
        }
    }
}

#[test]
fn cli_cache_run_lease_defers_clean_and_second_run_until_marker_refresh() {
    let fixture = CacheFixture::new();
    let cargo = write_cargo(
        fixture.owner.path(),
        "touch \"$READY\"\nwhile test ! -e \"$RELEASE\"; do sleep 0.01; done\n",
    );
    let ready = fixture.owner.path().join("ready");
    let release = fixture.owner.path().join("release");
    fixture.age_marker();
    let mut child = RunningChild(Some(
        fixture
            .command("run")
            .arg("--")
            .arg(&cargo)
            .arg("build")
            .env("READY", &ready)
            .env("RELEASE", &release)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap(),
    ));
    let deadline = Instant::now() + Duration::from_secs(10);
    while !ready.exists() {
        assert!(
            Instant::now() < deadline,
            "управляемая дочерняя команда не сообщила о готовности"
        );
        assert!(
            child.0.as_mut().unwrap().try_wait().unwrap().is_none(),
            "управляемая дочерняя команда завершилась до сообщения о готовности"
        );
        std::thread::sleep(Duration::from_millis(10));
    }
    assert!(
        fixture.last_used() > 1,
        "перед запуском дочерней команды маркер должен обновляться"
    );
    fixture.age_marker();
    let artifact = fixture.cache_dir.join("target/artifact");
    fs::create_dir_all(artifact.parent().unwrap()).unwrap();
    fs::write(&artifact, [42_u8; 8192]).unwrap();
    let local_target = fixture.root.join("target");
    fs::create_dir(&local_target).unwrap();
    fs::write(
        local_target.join("CACHEDIR.TAG"),
        b"Signature: 8a477f597d28d172789f06886806bc55\nGenerated by Cargo\n",
    )
    .unwrap();
    fs::write(local_target.join("artifact"), [42_u8; 8192]).unwrap();
    let local_before = directory_entry_names(&local_target);
    let local_bytes_before = allocated_bytes(&local_target);
    let clean = invoke(
        &fixture.root,
        &fixture.policy,
        &fixture.temp_root,
        &fixture.cache_home,
        true,
    );
    assert_eq!(clean.status.code(), Some(2), "{}", json(&clean));
    assert!(
        json(&clean)["error"]
            .as_str()
            .unwrap()
            .contains("блокировку обслуживания")
    );
    assert!(artifact.exists());
    assert_eq!(directory_entry_names(&local_target), local_before);
    assert_eq!(allocated_bytes(&local_target), local_bytes_before);
    assert_eq!(fixture.last_used(), 1);
    let second = fixture
        .command("run")
        .arg("--")
        .arg(&cargo)
        .arg("build")
        .output()
        .unwrap();
    assert_eq!(second.status.code(), Some(2), "{}", json(&second));
    assert_eq!(fixture.last_used(), 1);
    fs::write(&release, "").unwrap();
    let output = child.0.take().unwrap().wait_with_output().unwrap();
    assert!(output.status.success(), "{}", json(&output));
    assert!(
        fixture.last_used() > 1,
        "после завершения дочерней команды маркер должен обновляться"
    );
    let after = fixture
        .command("run")
        .arg("--")
        .arg(&cargo)
        .arg("build")
        .env("READY", &ready)
        .env("RELEASE", &release)
        .output()
        .unwrap();
    assert!(after.status.success(), "{}", json(&after));
}

#[test]
fn cli_partial_tmp_inventory_is_reported_without_fatal_exit() {
    let fixture = CacheFixture::new();
    let unreadable = fixture.temp_root.join("unreadable-foreign-directory");
    fs::create_dir(&unreadable).unwrap();
    fs::write(unreadable.join("hidden"), "foreign data").unwrap();
    fs::set_permissions(&unreadable, fs::Permissions::from_mode(0o000)).unwrap();
    let output = invoke_scan(
        &fixture.root,
        &fixture.policy,
        &fixture.temp_root,
        &fixture.cache_home,
    );
    fs::set_permissions(&unreadable, fs::Permissions::from_mode(0o700)).unwrap();
    assert!(output.status.success(), "{}", json(&output));
    let report = json(&output);
    assert_eq!(report["fatal_errors"], 0);
    assert!(
        report["tmp"]
            .as_array()
            .unwrap()
            .iter()
            .any(
                |inventory| inventory["root"] == fixture.temp_root.to_str().unwrap()
                    && inventory["complete"] == false
            )
    );
    assert!(unreadable.join("hidden").exists());
}

#[test]
fn cli_destructive_cleanup_failure_returns_non_success() {
    let owner = TempWorkspace::create("repository-maintenance-clean-failure-test").unwrap();
    let root = owner.path().join("checkout");
    let target = root.join("target");
    let temp_root = owner.path().join("tmp-sandbox");
    let cache_home = owner.path().join("cache-home");
    let cargo_home = owner.path().join("cargo-home");
    let cargo_bin = owner.path().join("mock-bin");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(&target).unwrap();
    fs::create_dir_all(&temp_root).unwrap();
    fs::create_dir_all(&cache_home).unwrap();
    fs::create_dir_all(&cargo_home).unwrap();
    fs::create_dir_all(&cargo_bin).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname=\"gc_clean_failure_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[workspace]\n",
    )
    .unwrap();
    fs::write(root.join("Cargo.lock"), "version = 3\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() {}\n").unwrap();
    fs::write(
        target.join("CACHEDIR.TAG"),
        b"Signature: 8a477f597d28d172789f06886806bc55\nGenerated by Cargo\n",
    )
    .unwrap();
    fs::write(target.join("synthetic-artifact"), [0x42_u8; 8192]).unwrap();

    let metadata = owner.path().join("metadata.json");
    fs::write(
        &metadata,
        serde_json::to_vec(&serde_json::json!({
            "workspace_root": root,
            "target_directory": target,
        }))
        .unwrap(),
    )
    .unwrap();
    write_cargo(
        &cargo_bin,
        &format!(
            "if [ \"${{1-}}\" = metadata ]; then\n  exec /bin/cat {}\nfi\nprintf '%s\\n' 'синтетическая ошибка cargo clean' >&2\nexit 42\n",
            shell_quote(&metadata)
        ),
    );

    let policy = owner.path().join("policy.toml");
    fs::write(
        &policy,
        "target_warning_gib=1\ntarget_hard_limit_gib=2\ntarget_warning_bytes=1\ntarget_hard_limit_bytes=2\nexternal_cache_hard_limit_gib=3\nexternal_cache_goal_gib=1\nexternal_cache_hard_limit_bytes=3\nexternal_cache_goal_bytes=1\nexternal_cache_min_age_days=7\nexternal_cache_min_age_seconds=1\norphan_min_age_hours=24\norphan_min_age_seconds=3600\ntmp_top_entries=1\n",
    )
    .unwrap();
    let runtime = private_runtime(&cache_home);
    let mut search_path = vec![cargo_bin];
    if let Some(existing) = std::env::var_os("PATH") {
        search_path.extend(std::env::split_paths(&existing));
    }
    let search_path = std::env::join_paths(search_path).unwrap();
    let output = Command::new(BINARY)
        .args([
            "clean",
            "--workspace-root",
            root.to_str().unwrap(),
            "--policy",
            policy.to_str().unwrap(),
            "--temp-root",
            temp_root.to_str().unwrap(),
            "--json",
            "--apply",
        ])
        .env("PATH", search_path)
        .env("XDG_CACHE_HOME", &cache_home)
        .env("XDG_RUNTIME_DIR", runtime)
        .env("TMPDIR", &temp_root)
        .env("CARGO_HOME", cargo_home)
        .env_remove("CARGO_BUILD_BUILD_DIR")
        .output()
        .unwrap();

    assert!(!output.status.success(), "stdout={}", json(&output));
    let report = json(&output);
    assert_eq!(report["cargo_target"]["action"], "error", "{report}");
    assert_eq!(report["cargo_target"]["result"], "failed", "{report}");
    assert_eq!(report["fatal_errors"], 1, "{report}");
    assert!(
        report["cargo_target"]["error"]
            .as_str()
            .unwrap()
            .contains("синтетическая ошибка cargo clean"),
        "{report}"
    );
    assert!(target.join("synthetic-artifact").exists());
}

fn private_runtime(cache_home: &Path) -> PathBuf {
    let runtime = cache_home.join("runtime");
    fs::create_dir_all(&runtime).unwrap();
    fs::set_permissions(&runtime, fs::Permissions::from_mode(0o700)).unwrap();
    runtime
}

fn write_cargo(directory: &Path, body: &str) -> PathBuf {
    let cargo = directory.join("cargo");
    fs::write(&cargo, format!("#!/bin/sh\nset -eu\n{body}")).unwrap();
    fs::set_permissions(&cargo, fs::Permissions::from_mode(0o700)).unwrap();
    cargo
}

fn shell_quote(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', "'\\''"))
}

fn invoke(root: &Path, policy: &Path, temp_root: &Path, cache_home: &Path, apply: bool) -> Output {
    let runtime = private_runtime(cache_home);
    let mut command = Command::new(BINARY);
    command
        .args([
            "clean",
            "--workspace-root",
            root.to_str().unwrap(),
            "--policy",
            policy.to_str().unwrap(),
            "--temp-root",
            temp_root.to_str().unwrap(),
            "--json",
        ])
        .env("XDG_CACHE_HOME", cache_home)
        .env("XDG_RUNTIME_DIR", runtime)
        .env("TMPDIR", temp_root);
    if apply {
        command.arg("--apply");
    }
    command.output().unwrap()
}

fn invoke_scan(root: &Path, policy: &Path, temp_root: &Path, cache_home: &Path) -> Output {
    let runtime = private_runtime(cache_home);
    Command::new(BINARY)
        .args([
            "scan",
            "--workspace-root",
            root.to_str().unwrap(),
            "--policy",
            policy.to_str().unwrap(),
            "--temp-root",
            temp_root.to_str().unwrap(),
            "--json",
        ])
        .env("XDG_CACHE_HOME", cache_home)
        .env("XDG_RUNTIME_DIR", runtime)
        .env("TMPDIR", temp_root)
        .output()
        .unwrap()
}

fn json(output: &Output) -> Value {
    serde_json::from_slice(&output.stdout).unwrap_or_else(|error| {
        panic!(
            "некорректный JSON ({error}): {}",
            String::from_utf8_lossy(&output.stdout)
        )
    })
}

fn allocated_bytes(path: &Path) -> u64 {
    let mut total = 0_u64;
    for entry in fs::read_dir(path).unwrap() {
        let entry = entry.unwrap();
        let metadata = entry.metadata().unwrap();
        total = total.saturating_add(metadata.blocks() * 512);
    }
    total
}

fn directory_entry_names(path: &Path) -> Vec<OsString> {
    let mut entries = fs::read_dir(path)
        .unwrap()
        .map(|entry| entry.unwrap().file_name())
        .collect::<Vec<_>>();
    entries.sort();
    entries
}

fn uid() -> u32 {
    use std::os::unix::fs::MetadataExt;
    fs::metadata("/proc/self").unwrap().uid()
}
